{{- with .Values.celeryWorkers }}
{{- if and .enabled .serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pbms.celery-workers.serviceAccountName" $ }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .commonLabels "context" $) | nindent 4 }}
  {{- if .commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
