{{- with .Values.benePortalApi }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" $ }}-bene-portal-api
  labels: {{- include "common.labels.standard" (dict "customLabels" .commonLabels "context" $) | nindent 4 }}
  {{- if .commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .service.type }}
  {{- if (or (eq .service.type "LoadBalancer") (eq .service.type "NodePort")) }}
  externalTrafficPolicy: {{ .service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .service.type "LoadBalancer") (not (empty .service.loadBalancerIP))) }}
  loadBalancerIP: {{ .service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .service.port }}
      protocol: TCP
      targetPort: http
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .podLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: bene-portal-api
{{- end }}
{{- end }}
